services:
  database:
    image: postgres
    restart: unless-stopped
    hostname: ${DATABASE_HOSTNAME}
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - cc2_translator_data:/var/lib/postgresql/data

volumes:
  cc2_translator_data:
