- name: Configure Go Application and Node Exporter
  hosts: go_app_server
  become: yes
  tasks:
    # Tasks for Monitoring:
    - name: Install Prometheus Node Exporter
      apt:
        name: prometheus-node-exporter
        state: present
      notify: restart node exporter

    # Tasks for server deployment
    - name: Install Unzip
      apt:
        name: unzip
        state: present

    - name: Download Translator Server
      get_url: 
        url: 
        dest: /tmp/translator.zip
        mode: '0644'

    - name: Unzip binary
      unarchive:
        src: /tmp/translator.zip
        dest: /opt/translator
        remote_src: yes

    - name: Gcloud init
      notify: start translator server

  handlers:
    - name: restart node exporter
      systemd:
        name: prometheus-node-exporter
        state: restarted

    - name: start translator server
      command: /opt/translator/server
      async: 30
      poll: 0
