- name: Configure Go Application and Node Exporter
  hosts: go_app_server
  become: yes
  tasks:
    # Tasks for Monitoring:
    - name: Install Prometheus Node Exporter
      apt:
        name: prometheus-node-exporter
        state: present
      notify: restart node exporter

    - name: Create Directory
      ansible.builtin.file:
        path: /opt/translator
        state: directory

    - name: Download Translator Server
      get_url: 
        url: https://github.com/MetaEMK/DHBW-GCP-Translate/releases/download/testing/dhbw-gcp-translate
        dest: /opt/translator

  handlers:
    - name: restart node exporter
      systemd:
        name: prometheus-node-exporter
        state: restarted

    - name: start translator server
      command: /opt/translator/server
      async: 30
      poll: 0
