# This file contains the configuration for the application.

# hostname is not neccessary if you are using a cloud database but can be used for local databases
# db_hostname: 34.88.170.32
db_port: 5432
db_username: postgres
db_password: my_password
db_name: translator
db_instance_connection_name: cc2-translator:europe-north1:translator-database
keyfile_path: ./keyfile.json
